### PR TITLE
Display Rails/Paths for objects

### PR DESCRIPTION
**Pull request by savage13**
Display Rails/Paths for objects

- All objects will `LinksToRails` will request Rails data
- Added ColorScale in `src/util/colorscale.ts` 
- Added hotline in `src/util/leaflet.hotline.js`
   - This draws the polyline in color.
   - This was added directly a couple of functions needed to be added
- Added a `persistentRails` instance in `staticData`

Addition of new Rails will modify the colorscale using the y-value min/max of all visible rails, see below.

The Colorscale can be changed by mousing over the current colorscale and picking a new scale, last image.

All Dragons
Screenshot 2022-06-14 at 15-20-46 BotW Object Map

Guardian Skywatchers above Hyrule Castle
Screenshot 2022-06-14 at 15-22-45 BotW Object Map

Moldugas with ColorScale changer
Screen Shot 2022-06-14 at 3 25 56 PM

Sorry about the size of this request.  The colorscale and polyline hopefully are not too complex.

Thanks again :D

---
This change is [Reviewable](https://reviewable.io/reviews/zeldamods/objmap/97)

### CODE REVIEW

**Review by leoetlino — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldamods/objmap/97)* status: all files reviewed, 8 unresolved discussions (waiting on @savage13)

___
*[`src/App.css` line 148 at r1](https://reviewable.io/reviews/zeldamods/objmap/97#-N4hwPUB28w7OlGpoRFH:-N4hwPUB28w7OlGpoRFI:b-ldlxrt) ([raw file](https://github.com/zeldamods/objmap/blob/da16a5875dc8a66b2f4536c74183c4201a20a59f/src/App.css#L148)):*
> ```CSS
>     position: absolute;
>     display: inline;
>     //bottom: 0;
> ```

should be removed (also CSS doesn't support // comments)
___
*[`src/components/AppMapDetailsObj.ts` line 175 at r1](https://reviewable.io/reviews/zeldamods/objmap/97#-N4hxH7Z2_mPG4GRGyg2:-N4hxH7Z2_mPG4GRGyg3:b8iimht) ([raw file](https://github.com/zeldamods/objmap/blob/da16a5875dc8a66b2f4536c74183c4201a20a59f/src/components/AppMapDetailsObj.ts#L175)):*
> ```XML
>   }
> ```

This new line should be removed
___
*[`src/components/AppMapDetailsObj.ts` line 180 at r1](https://reviewable.io/reviews/zeldamods/objmap/97#-N4hxJljDq9Atby095oQ:-N4hxJljDq9Atby095oR:blmmebf) ([raw file](https://github.com/zeldamods/objmap/blob/da16a5875dc8a66b2f4536c74183c4201a20a59f/src/components/AppMapDetailsObj.ts#L180)):*
> ```XML
>       return;
> 
>     if (this.obj.korok_type && this.obj.korok_type == "Moving Lights") {
> ```

nit: this probably shouldn't be braced (the previous if statement isn't)
___
*[`src/components/AppMapDetailsObj.ts` line 217 at r1](https://reviewable.io/reviews/zeldamods/objmap/97#-N4hxsRJ2d3tAYf8guvU:-N4hxsRJ2d3tAYf8guvV:bjt2qzb) ([raw file](https://github.com/zeldamods/objmap/blob/da16a5875dc8a66b2f4536c74183c4201a20a59f/src/components/AppMapDetailsObj.ts#L217)):*
> ```XML
>     }
>   }
>   getRailsLimits(rMarkers: any[]) {
> ```

there should be another new line before this function
___
*[`src/components/AppMapDetailsObj.ts` line 274 at r1](https://reviewable.io/reviews/zeldamods/objmap/97#-N4hyJAR5hyrxDGgw3Uj:-N4hyJAR5hyrxDGgw3Uk:b-30m12z) ([raw file](https://github.com/zeldamods/objmap/blob/da16a5875dc8a66b2f4536c74183c4201a20a59f/src/components/AppMapDetailsObj.ts#L274)):*
> ```XML
>     this.railMarkers.forEach(m => m.remove());
>     // Rails
>     this.updateColorScale();
> ```

Why does the color scale need to be updated if we're getting rid of it anyway?
___
*[`src/components/AppMapDetailsObj.vue` line 27 at r1](https://reviewable.io/reviews/zeldamods/objmap/97#-N4hyQOvCbawHNIXxv4a:-N4hyQOvCbawHNIXxv4b:bekqjfc) ([raw file](https://github.com/zeldamods/objmap/blob/da16a5875dc8a66b2f4536c74183c4201a20a59f/src/components/AppMapDetailsObj.vue#L27)):*
> ```Vue
>       </section>
>       <section class="mt-2" v-show="this.railMarkers.length || staticData.persistentRailMarkers.length">
>         <b-btn v-show="this.railMarkers.length" size="sm" block variant="dark" @click="keepRailMarkersAlive()">Keep Rails markers loaded</b-btn>
> ```

the word "markers" is probably unnecessary here
___
*[`src/components/AppMapDetailsObj.vue` line 28 at r1](https://reviewable.io/reviews/zeldamods/objmap/97#-N4hyYmR1uv-wsrziZ5r:-N4hyYmR1uv-wsrziZ5s:b-7ropln) ([raw file](https://github.com/zeldamods/objmap/blob/da16a5875dc8a66b2f4536c74183c4201a20a59f/src/components/AppMapDetailsObj.vue#L28)):*
> ```Vue
>       <section class="mt-2" v-show="this.railMarkers.length || staticData.persistentRailMarkers.length">
>         <b-btn v-show="this.railMarkers.length" size="sm" block variant="dark" @click="keepRailMarkersAlive()">Keep Rails markers loaded</b-btn>
>         <b-btn v-show="staticData.persistentRailMarkers.length" size="sm" block variant="dark" @click="forgetPersistentRailMarkers()">Hide Rail markers</b-btn>
> ```

ditto
___
*[`src/util/leaflet.hotline.js` line 1 at r1](https://reviewable.io/reviews/zeldamods/objmap/97#-N4hwpsP4NfbFmYs1wes:-N4hwpsP4NfbFmYs1wet:brmy466) ([raw file](https://github.com/zeldamods/objmap/blob/da16a5875dc8a66b2f4536c74183c4201a20a59f/src/util/leaflet.hotline.js#L1)):*
> ```JavaScript
> /*
> ```

This should be installed via npm rather than vendored.

**Comment by savage13** [comment]
I am reminded of why I included leaflet.hotline.js library directly.  The library does not provide a method to change which leaflet map pane the line is drawn on.  If the lines are drawn on the default pane (`overlayPane` I think), it blocks the mouse over for other objects (search markers).  I see two ways around this, either:
- included it directly in the code base or 
- fork the code, create an updated version, and install that one

Thoughts?

**Comment by leoetlino** [comment]
> fork the code, create an updated version, and install that one

I think this is probably the better option, as that makes it easier to reuse the (modified) code

**Review by savage13 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeldamods/objmap/97)* status: all files reviewed, 7 unresolved discussions (waiting on @leoetlino)

___
*[`src/App.css` line 148 at r1](https://reviewable.io/reviews/zeldamods/objmap/97#-N4hwPUB28w7OlGpoRFH:-N4i5Wk7CZdlcDr1-bTg:b-896fix) ([raw file](https://github.com/zeldamods/objmap/blob/da16a5875dc8a66b2f4536c74183c4201a20a59f/src/App.css#L148)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

should be removed (also CSS doesn't support // comments)
</blockquote></details>

Done.
___
*[`src/components/AppMapDetailsObj.ts` line 175 at r1](https://reviewable.io/reviews/zeldamods/objmap/97#-N4hxH7Z2_mPG4GRGyg2:-N4i5d-c-ZWpPjJg3JlE:b-896fix) ([raw file](https://github.com/zeldamods/objmap/blob/da16a5875dc8a66b2f4536c74183c4201a20a59f/src/components/AppMapDetailsObj.ts#L175)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This new line should be removed
</blockquote></details>

Done.
___
*[`src/components/AppMapDetailsObj.ts` line 180 at r1](https://reviewable.io/reviews/zeldamods/objmap/97#-N4hxJljDq9Atby095oQ:-N4i5lX0DvmQoF_q-2qd:bb6un1j) ([raw file](https://github.com/zeldamods/objmap/blob/da16a5875dc8a66b2f4536c74183c4201a20a59f/src/components/AppMapDetailsObj.ts#L180)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

nit: this probably shouldn't be braced (the previous if statement isn't)
</blockquote></details>

Done
___
*[`src/components/AppMapDetailsObj.ts` line 217 at r1](https://reviewable.io/reviews/zeldamods/objmap/97#-N4hxsRJ2d3tAYf8guvU:-N4i5oqm2Nf0mVM6wMsR:b-896fix) ([raw file](https://github.com/zeldamods/objmap/blob/da16a5875dc8a66b2f4536c74183c4201a20a59f/src/components/AppMapDetailsObj.ts#L217)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

there should be another new line before this function
</blockquote></details>

Done.
___
*[`src/components/AppMapDetailsObj.ts` line 274 at r1](https://reviewable.io/reviews/zeldamods/objmap/97#-N4hyJAR5hyrxDGgw3Uj:-N4i62GEEOW2dw75wKTO:b9k8meq) ([raw file](https://github.com/zeldamods/objmap/blob/da16a5875dc8a66b2f4536c74183c4201a20a59f/src/components/AppMapDetailsObj.ts#L274)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

Why does the color scale need to be updated if we're getting rid of it anyway?
</blockquote></details>

The ColorScale (within the staticData) is defined by the current object's rails min/max and those from the persistentRails in staticData. We need to update the colorScale here to account for the current's objects rail has been removed.
___
*[`src/components/AppMapDetailsObj.vue` line 27 at r1](https://reviewable.io/reviews/zeldamods/objmap/97#-N4hyQOvCbawHNIXxv4a:-N4i6kci1u7C53RuoLNN:bhysp0m) ([raw file](https://github.com/zeldamods/objmap/blob/da16a5875dc8a66b2f4536c74183c4201a20a59f/src/components/AppMapDetailsObj.vue#L27)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

the word "markers" is probably unnecessary here
</blockquote></details>

Removed "markers"
___
*[`src/components/AppMapDetailsObj.vue` line 28 at r1](https://reviewable.io/reviews/zeldamods/objmap/97#-N4hyYmR1uv-wsrziZ5r:-N4i6oktB-erdzVvlfbE:b-896fix) ([raw file](https://github.com/zeldamods/objmap/blob/da16a5875dc8a66b2f4536c74183c4201a20a59f/src/components/AppMapDetailsObj.vue#L28)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`src/util/leaflet.hotline.js` line 1 at r1](https://reviewable.io/reviews/zeldamods/objmap/97#-N4hwpsP4NfbFmYs1wes:-N4lM78p2Xw1KsTjkCUj:b-n45ayt) ([raw file](https://github.com/zeldamods/objmap/blob/da16a5875dc8a66b2f4536c74183c4201a20a59f/src/util/leaflet.hotline.js#L1)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

This should be installed via npm rather than vendored.
</blockquote></details>

Done. Forked and installed directly from github. To keep the changes on hotline to a minimum I rewrote the logic that handles the y-limits on the persistent Rails.

package.json was modified

**Review by leoetlino — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldamods/objmap/97)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @savage13)

**Pull request merged**
